build:
	gcc -g -L../mlx -L../mlx_beta -L./get_next_line -L./libft -lmlx -framework OpenGL -framework AppKit ./src/*.c ./get_next_line/*.c ./libft/*.c libmlx.dylib -o raycast;

run:
	./raycast map_conf.cub;

clean:
	rm raycast;
